# Generated by Django 2.2.2 on 2019-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='用户名')),
                ('secret', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '超神学院',
                'verbose_name_plural': '超神学院',
                'db_table': 'SuperSchool',
            },
        ),
    ]
