# Generated by Django 2.2.2 on 2019-07-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clossroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=32, verbose_name='战斗学宫编号')),
                ('c_name', models.CharField(max_length=32, verbose_name='战斗学宫名')),
            ],
            options={
                'verbose_name': '战斗学宫',
                'verbose_name_plural': '战斗学宫',
                'db_table': 'Clossroom',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=32, verbose_name='最强王者编号')),
                ('t_name', models.CharField(max_length=32, verbose_name='最强王者称号')),
                ('t_num', models.IntegerField(default=0, verbose_name='最强王者收徒数')),
            ],
            options={
                'verbose_name': '最强王者表',
                'verbose_name_plural': '最强王者表',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=32, verbose_name='召唤师学号')),
                ('s_name', models.CharField(max_length=32, verbose_name='召唤师名称')),
                ('s_tel', models.IntegerField(default=0, verbose_name='召唤师麦段')),
                ('s_gender', models.CharField(max_length=10, verbose_name='召唤师性别')),
                ('s_classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Clossroom', verbose_name='关联战斗学宫')),
            ],
            options={
                'verbose_name': '召唤师',
                'verbose_name_plural': '召唤师',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_id', models.CharField(max_length=32, verbose_name='战场区')),
                ('co_name', models.CharField(max_length=32, verbose_name='战场名')),
                ('co_score', models.IntegerField(default=0, verbose_name='几杀')),
                ('co_teacher', models.ManyToManyField(to='login_app.Teacher', verbose_name='关联最强王者')),
            ],
            options={
                'verbose_name': '战场定位',
                'verbose_name_plural': '战场定位',
                'db_table': 'Course',
            },
        ),
    ]
