# Generated by Django 2.2.2 on 2019-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_clossroom_course_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='co_id',
            field=models.CharField(max_length=32, verbose_name='战场辨明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='co_score',
            field=models.CharField(max_length=10, verbose_name='几杀'),
        ),
    ]
