# Generated by Django 2.2.2 on 2019-07-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20190712_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='clossroom',
            name='c_teacher',
            field=models.ManyToManyField(to='login_app.Teacher', verbose_name='多对多关联老师'),
        ),
    ]
